version: 2
updates:
  - package-ecosystem: "composer"
    directory: "/"
    schedule:
      interval: "daily"
    allow:
      - dependency-name: "phpstan/phpstan"
      - dependency-name: "rector/rector"
    versioning-strategy: increase
