services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Brotkrueml\JobRouterData\:
    resource: '../Classes/*'

  querybuilder.tx_jobrouterdata_domain_model_transfer:
    class: 'TYPO3\CMS\Core\Database\Query\QueryBuilder'
    factory:
      - '@TYPO3\CMS\Core\Database\ConnectionPool'
      - 'getQueryBuilderForTable'
    arguments:
      - 'tx_jobrouterdata_domain_model_transfer'

  Brotkrueml\JobRouterData\Command\CleanUpTransfersCommand:
    tags:
      - name: 'console.command'
        command: 'jobrouter:data:cleanuptransfers'
        description: 'Delete old entries in the transfer table'
        schedulable: true

  Brotkrueml\JobRouterData\Command\SyncCommand:
    tags:
      - name: 'console.command'
        command: 'jobrouter:data:sync'
        description: 'Synchronise JobData data sets from JobRouter installations'
        schedulable: true

  Brotkrueml\JobRouterData\Command\TransmitCommand:
    tags:
      - name: 'console.command'
        command: 'jobrouter:data:transmit'
        description: 'Transmit data sets to JobData tables'
        schedulable: true

  Brotkrueml\JobRouterData\Controller\TableAjaxController:
    tags: [ 'backend.controller' ]

  Brotkrueml\JobRouterData\Domain\Repository\QueryBuilder\TransferRepository:
    arguments:
      $queryBuilder: '@querybuilder.tx_jobrouterdata_domain_model_transfer'

  Brotkrueml\JobRouterData\EventListener\ToolbarItemProvider:
    tags:
      - name: event.listener
        identifier: 'jobrouter-data/toolbar-item-provider'
        event: TYPO3\CMS\Backend\Backend\Event\SystemInformationToolbarCollectorEvent
