services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Brotkrueml\JobRouterData\:
    resource: '../Classes/*'
    exclude: '../Classes/{Domain/Entity,Domain/Model,Exception,Extension.php,Hooks,UserFunctions}'

  Brotkrueml\JobRouterData\Command\CleanUpTransfersCommand:
    tags:
      - name: 'console.command'
        command: 'jobrouter:data:cleanuptransfers'
        description: 'Delete old entries in the transfer table'
        schedulable: true

  Brotkrueml\JobRouterData\Command\SyncCommand:
    tags:
      - name: 'console.command'
        command: 'jobrouter:data:sync'
        description: 'Synchronise JobData data sets from JobRouter installations'
        schedulable: true

  Brotkrueml\JobRouterData\Command\TransmitCommand:
    tags:
      - name: 'console.command'
        command: 'jobrouter:data:transmit'
        description: 'Transmit data sets to JobData tables'
        schedulable: true

  Brotkrueml\JobRouterData\Controller\TableTestController:
    tags: [ 'backend.controller' ]

  Brotkrueml\JobRouterData\Domain\Converter\DatasetConverter:
    public: true

  Brotkrueml\JobRouterData\EventListener\ToolbarItemProvider:
    tags:
      - name: event.listener
        identifier: 'jobrouter-data/toolbar-item-provider'
        event: TYPO3\CMS\Backend\Backend\Event\SystemInformationToolbarCollectorEvent

  Brotkrueml\JobRouterData\EventListener\IntegerFormatter:
    tags:
      - name: event.listener
        identifier: 'jobrouter-data/integer-formatter'
        event: Brotkrueml\JobRouterData\Event\ModifyColumnContentEvent

  Brotkrueml\JobRouterData\EventListener\DecimalFormatter:
    tags:
      - name: event.listener
        identifier: 'jobrouter-data/decimal-formatter'
        event: Brotkrueml\JobRouterData\Event\ModifyColumnContentEvent

  Brotkrueml\JobRouterData\EventListener\DateFormatter:
    tags:
      - name: event.listener
        identifier: 'jobrouter-data/date-formatter'
        event: Brotkrueml\JobRouterData\Event\ModifyColumnContentEvent

  Brotkrueml\JobRouterData\EventListener\DateTimeFormatter:
    tags:
      - name: event.listener
        identifier: 'jobrouter-data/datetime-formatter'
        event: Brotkrueml\JobRouterData\Event\ModifyColumnContentEvent
