services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  JobRouter\AddOn\Typo3Data\:
    resource: '../Classes/*'
    exclude: '../Classes/{Domain/Dto,Domain/Entity,Exception,Extension.php,Hooks,UserFunctions}'

  JobRouter\AddOn\Typo3Data\DataProcessing\TableProcessor:
    public: true

  JobRouter\AddOn\Typo3Data\Domain\Converter\DatasetConverter:
    public: true

  # Set public for functional tests
  JobRouter\AddOn\Typo3Data\Domain\Repository\TransferRepository:
    public: true

  JobRouter\AddOn\Typo3Data\EventListener\ToolbarItemProvider:
    tags:
      - name: event.listener
        identifier: 'jobrouter-data/toolbar-item-provider'
        event: TYPO3\CMS\Backend\Backend\Event\SystemInformationToolbarCollectorEvent

  JobRouter\AddOn\Typo3Data\EventListener\IntegerFormatter:
    tags:
      - name: event.listener
        identifier: 'jobrouter-data/integer-formatter'

  JobRouter\AddOn\Typo3Data\EventListener\DecimalFormatter:
    tags:
      - name: event.listener
        identifier: 'jobrouter-data/decimal-formatter'

  JobRouter\AddOn\Typo3Data\EventListener\DateFormatter:
    tags:
      - name: event.listener
        identifier: 'jobrouter-data/date-formatter'

  JobRouter\AddOn\Typo3Data\EventListener\DateTimeFormatter:
    tags:
      - name: event.listener
        identifier: 'jobrouter-data/datetime-formatter'

  JobRouter\AddOn\Typo3Data\Hooks\TableUpdateHook:
    public: true

  JobRouter\AddOn\Typo3Data\Preview\ContentElementPreviewRenderer:
    public: true

  JobRouter\AddOn\Typo3Data\Synchronisation\SimpleTableSynchroniser:
    arguments:
      $cache: '@cache.pages'

  JobRouter\AddOn\Typo3Data\UserFunctions\FormEngine\CustomTables:
    public: true
